export const FETCH_POPULAR_SERIES_REQUEST = 'FETCH_POPULAR_SERIES_REQUEST';
export const FETCH_POPULAR_SERIES_SUCCESS = 'FETCH_POPULAR_SERIES_SUCCESS';
export const FETCH_POPULAR_SERIES_FAILURE = 'FETCH_POPULAR_SERIES_FAILURE';
